### ISSUE TITLE
Paper link in README is not working

### ISSUE THREAD

**Issue by ouhenio** [google/lecam-gan#2]
Hi!

The paper link in the readme points to https://github.com/google/lecam-gan/blob/master, which I assume is a mistake. My first thought was that this was maybe by design since CVPR2021 is in June and so the paper isn't public yet, but then I found it [here](https://faculty.ucmerced.edu/mhyang/papers/cvpr2021_gan_limited_data.pdf), so I guess this is not the case.

Thanks for your work btw!

**Comment by hytseng0509** [comment]
I've updated the ArXiv paper link. Thanks for pointing it out!
