### ISSUE TITLE
Decay factor is 0.99 in the paper but 0.9 in the code

### ISSUE THREAD

**Issue by edward3862** [google/lecam-gan#3]
Hello, thanks for sharing this helpful repo! I found that in your code the decay factor is 0.9 which is reported as 0.99 in the paper. Although this is not a critical problem, which value should I exactly use to better reproduce the performance in the paper?

Paper:
> We ﬁx the decay factor γ to 0.99 in all experiments.

Code:
https://github.com/google/lecam-gan/blob/f9af9485eda4637b25e694c142ce8e6992eb7243/third_party/utils.py#L638

Best.

**Comment by hytseng0509** [comment]
Hi,

Thanks for the interest in this work. We use 0.9 for the CIFAR experiments and 0.99 for the StyleGAN2 model. However, from my experience, using 0.99 for the CIFAR experiments should not make an obvious difference.

**Comment by edward3862** [comment]
Thank you very much!
