### ISSUE TITLE
Training stylegan 2

### ISSUE THREAD

**Issue by KasparPeterson** [google/lecam-gan#4]
Hello!

Thanks for the great paper and code! 

Unfortunately I am having some issues with integrating the lecam_loss.py with the original stylegan2-ada repo. 

I tried hardcoding the functionality of the lecam_loss.py function into the stylegan2 loss in [here](https://github.com/NVlabs/stylegan2-ada/blob/main/training/loss.py). It trains but it starts producing aliens and in it quite quickly turns into green images.

Could you please clarify how it is done in more detail?

**Comment by hytseng0509** [comment]
Thanks for the interest in this work.
What's the weight of the lemcam_loss?

**Comment by roadjiang** [comment]
Please look at our code for the correct lambda weight (much smaller) for stylegan2.
