### ISSUE TITLE
Do you have the version implemented by Pytorch?

### ISSUE THREAD

**Issue by sunpeng1996** [google/lecam-gan#6]
Hi，thanks for your great work.
Do you have the version implemented by Pytorch?

**Comment by hytseng0509** [comment]
Hi,

Thanks for your interest in this work. We use Pytorch to apply our method for training/evaluating the BigGAN model on the CIFAR dataset. Please see the code [here](https://github.com/google/lecam-gan/tree/master/biggan_cifar).
