### ISSUE TITLE
The formula in the paper

### ISSUE THREAD

**Issue by faduo** [google/lecam-gan#8]
The **formula (4)**  in the paper is 
R_{LC}= E_{x∼T}[||D(x)−\alpha_{F}||^2]+ E_{z∼p_z}[||D(G(z))−\alpha_R||^2] 
but according to my understanding, this will not make the result converge to a certain point stably, but will cause the result to oscillate, and this does not conform to the **legend (2)** in the paper, is this a clerical error?

**Comment by roadjiang** [comment]
Please see Proposition 1 (Appendix A.2 and A.3), in theory under mild assumptions this term + WGAN converges.
In practice, we find in all experiments, the models converge to stationary points (like plotted in Fig. 8).

I am not sure what you mean by legend (2)
