### ISSUE TITLE
Implementation for StyleGAN2

### ISSUE THREAD

**Issue by mshahbazi72** [google/lecam-gan#9]
Hi
I noticed there is only the code for Lecam regularizer in the StyleGAN2 folder. Is the full implementation not available in the repo? Are we supposed to manually add the regularizer to the official StyleGAN2 code ourselves?

**Comment by roadjiang** [comment]
Yes, it should be an easy job.
We have tested the code with StyleGAN2 which reproduced our results as expected. 
We did not include the StyleGAN2 code in our third_party due to the copyright of StyleGAN2 code.
